#!/usr/bin/python3
#
# Convert HTML to Markdown 
#

import sys,os,re

TAG='sound'

def html2markdown(TAG):

    for fn in os.listdir('blog/'+ TAG +'/_posts/'):
        code=None
        with open('blog/' + TAG + '/_posts/' + fn) as f:
            for l in f:
                if 'iframe' in l:
                    code = re.sub('.*embed/(.+)" frame.*', '\\1', l)
        if code:
            print("sed -i '3i media: " +  code.strip() +  "' " + fn)
            print("sed -i '/iframe/d' " + fn)

def markdown2markdown(TAG):

    for fn in os.listdir('blog/'+ TAG +'/_posts/'):
        code=None
        print('echo ' + fn)
        with open('blog/' + TAG + '/_posts/' + fn) as f:
            for l in f:
                if 'title' in l and '-' in l:
                    t = l.split('-')
                    author = re.sub('title: (.*)', '\\1', t[0].strip())
                    title = t[1].strip().replace("'","\\x27")
                    print("sed -i 's#\(title: \).*#\\1" + title + "#' " + fn)
                    print("sed -i '3i author: " +  author +  "' " + fn)

markdown2markdown(TAG)

sys.exit(0)

