#!/usr/bin/python3
#
# Interactive Jekyll post CLI tool
#

import sys,os,re
from datetime import datetime

VERSION='1.2'

TAG=['tech','cyber','poi','book','sound','other']

# DEF

def get_index(tag):
    index = 1
    for f in os.listdir('blog/'+ tag + '/_posts/'):
        i = int(re.sub('.*' + tag + '-(.*)\.md','\\1', f))
        if i > index: index = i
    return str(index + 1)

#----------------------------------------------------

print("\n-- Post composer "+ VERSION + " --\n")

# HEADER

header,title,author,media,rating,tag = '','','',''

while not tag in TAG: tag = input("Tag: ")
while not title: title = input("Title: ")
if tag in ['poi','book','sound']: author = input("Author: ")
if tag in ['poi','sound']: media = input("Media: ")
if tag == 'book': rating = input("Rating: ")

header += '---' + '\n'
header +='title: ' + title + '\n'
if author: header +='author: ' + author + '\n'
if media: header +='media: ' + media + '\n'
if rating: header += 'rating: ' + rating + '\n'

header += 'layout: post\n'
header += 'tags: ' + tag + '\n'
header += 'date: ' + datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S') + '\n'
header += '---' + '\n'

# CONTENT

content,text = '',''

while 1:
    image = input("Insert image URL: ")
    if image == '.': break
    if image: content += '<img width="200" src="' + image + '" />\n'
while 1:
    link = input("Insert link URL: ")
    if link == '.': break
    if link: content += '\n<a target="_blank" href="' + link + '">' + re.sub('.*://','',link) + '</a>\n'
while 1:
    line = input("Insert text: ")
    if line == '.': break
    if line: text += line + '\n'

if text: content += '\n' +  text + '\n'
    
# PREVIEW

preview = input("\nShow preview? [y/n]: ")
if preview == 'y': print(header + content)

# WRITE

fn = datetime.utcnow().strftime('%Y-%m-%d') + '-' + tag + '-' + get_index(tag) +'.md'
write = input('Write to file [ blog/' + tag + '/_posts/' + fn + ' ]? [y/n]: ')
if write == 'y':
    try:
        f = open('blog/' +tag + '/_posts/' + fn, 'a')
        f.write(header + content)
        f.close()
        print("Done.")
    except:
        print("Write error.")

sys.exit(0)
