#!/usr/bin/python3
#
# Interactive Jekyll post CLI tool
#

import yaml,sys,os,re
from yaml import safe_dump
from datetime import datetime

VERSION='1.3'

TAG=['tech','cyber','poi','book','sound','other']

POST={'title':None,'layout':'post','tags':None,'date':datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}

CONTENT = ''

# INDEX

def get_index(tag):
    index = 1
    for f in os.listdir('blog/'+ tag + '/_posts/'):
        i = int(re.sub('.*' + tag + '-(.*)\.md', '\\1', f))
        if i > index: index = i
    return str(index + 1)

# MAIN

print("\n-- Post composer "+ VERSION + " --\n")

while not POST['tags'] in TAG: POST['tags'] = input("tag: ")
while not POST['title']: POST['title'] = input("title: ")

for attr in ['rating','author','media']:
    val = input(attr +  ': ')
    if val: POST[attr] = val

for attr in ['image','link']:
    while True:
        val = input(attr +  ': ')
        if not val: break
        if attr not in POST:
            POST[attr] = [val]
        else:
            POST[attr].append(val)

while True:
    line = input("text: ")
    if not line: break
    CONTENT += "\n" + line + "\n"

# PREVIEW

preview = input("\nShow preview? [y/n]: ")
if preview == 'y':
    print(safe_dump(POST, sort_keys=False, explicit_start=True, explicit_end=True) + CONTENT)

# WRITE

fn = datetime.utcnow().strftime('%Y-%m-%d') + '-' + POST['tags'] + '-' + get_index(POST['tags']) +'.md'

write = input('Write to file [ blog/' + POST['tags'] + '/_posts/' + fn + ' ]? [y/n]: ')
if write == 'y':
    with open('blog/' + POST['tags'] + '/_posts/' + fn, 'a') as f:
        f.write(safe_dump(POST, sort_keys=False, explicit_start=True, explicit_end=True) + CONTENT)
        print("Done.")

sys.exit(0)

