#!/usr/bin/python
#
# Interactive post CLI tool.
#

import time,os,re

TAG=['tech','poi','book','sound','other']

#---------------------------

def get_index(tag):
    index = 1
    for F in os.listdir('_posts/'):
        if tag in F:
            i = int(re.sub('.*' + tag + '-(.*)\.md','\\1',F))
            if i > index: index = i
    return str(index + 1)

#---------------------------

print "\n--# Post composer 1.1 #--\n"

# HEADER
header,title,rating,tag = '','','',''
while not tag in TAG: tag = raw_input("Tag: ")
while not title: title = raw_input("Title: ")
if tag == 'book':
    while not rating: rating = raw_input("Rating: ")

header +='---' + '\n'
header +='title: ' + title + '\n'
if rating: header += 'rating: ' + rating + '\n'
header += 'layout: post\n'
header +='tags: ' + tag + '\n'
header += 'date: ' + time.strftime('%Y-%m-%d %H:%M:%S') + '\n'
header +='---' + '\n'

# CONTENT
content,text = '',''
while 1:
    video = raw_input("Insert video URL: ")
    if video == '.': break
    if video: content += '<iframe width="603" height="452" src="' + video + '" frameborder="0"></iframe>\n'
while 1:
    image = raw_input("Insert image URL: ")
    if image == '.': break
    if image: content += '<img width="200" src="' + image + '" />\n'
while 1:
    link = raw_input("Insert link URL: ")
    if link == '.': break
    if link: content += '<a target="_blank" href="' + link + '">' + re.sub('.*://','',link) + '</a>\n'
while 1:
    line = raw_input("Insert text: ")
    if line == '.': break
    if line: text += line + '\n'
if text: content += '<p>\n' +  text + '</p>\n'
    
# PREVIEW
preview = raw_input("\nShow preview? [y/n]: ")
if preview == 'y': print header + content

# WRITE
fn = time.strftime('%Y-%m-%d') + '-' + tag + '-' + get_index(tag) +'.md'
write = raw_input('Write to file [ ' + fn + ' ]? [y/n]: ')
if write == 'y':
    try:
        f = open('_posts/' + fn, 'a')
        f.write(header + content)
        f.close()
        print "Done."
    except:
        print "Write error."

